name: Publish

on:
  push:
    branches: [ 'main' ]
    paths-ignore:
      - 'jarjar-gradle/**'
      - 'jarjar-gradle-demo/**'
      - '.github/workflows/**'
      - 'docs/**'
      - 'README.md'

permissions:
  contents: read

jobs:
  build:
    uses: MinecraftForge/SharedActions/.github/workflows/gradle.yml@v0
    with:
      java: 17
      gradle_tasks: 'check publish'
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      PROMOTE_ARTIFACT_WEBHOOK: ${{ secrets.PROMOTE_ARTIFACT_WEBHOOK }}
      PROMOTE_ARTIFACT_USERNAME: ${{ secrets.PROMOTE_ARTIFACT_USERNAME }}
      PROMOTE_ARTIFACT_PASSWORD: ${{ secrets.PROMOTE_ARTIFACT_PASSWORD }}
      GRADLE_CACHE_KEY: ${{ secrets.GRADLE_CACHE_KEY }}
